# Generated by Django 5.1 on 2024-08-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstn', '0002_user_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
    ]
